<div>
	<div class="lytkiri" >
		<img alt="image" src="./img/image1.png"/>
	</div>
	<div class = "lytkanan">
		<label>WELCOME TO OUR WEBSITE!!!</label>
		<div class="clear">
			<label>PC kamu bermasalah? Yuks diskusikan disini, Yakin deh langsung ada solusinya</label>
		</div>
		<div class="clear">
			<label>Nah, fungsi dari Website Diskusi Komputer ini agar menjadikan website yang bermanfaat</label>
		</div>
		<div class="clear">
			<label>untuk orang banyak yang ingin mendisusikan mengenai masalah PC.</label>
		</div>
	</div>		
</div>
